### ISSUE TITLE
Page-specific imba files?

### ISSUE THREAD

**Issue by jonbjornn** [judofyr/imba-rails#1]
Is there any way to setup page-specific, or more accurately, controller-specific imba files? Currently the asset pipeline docs (http://guides.rubyonrails.org/asset_pipeline.html#controller-specific-assets) say to use the following:

```
<%= javascript_include_tag params[:controller] %>
```

which would pull in the specific .js file for whatever controller (welcome.js for welcomecontroller etc...). Unfortunately this doesn't work for imba files since there would be no .imba extension for the gem to compile separately.

Say you have a file example.imba, it doesn't seem to work to `//= require example` within welcome.js either, it only works if the require statement is in application.js.

Just trying to avoid having all imba files pulled into every page of the app.

**Comment by judofyr** [comment]
It seems to work fine here. 64425f93805bbe9f7dd9db391c30d1e9f1a40e36 is the commit where I added page-specific Imba file for the `WelcomeController`.

**Comment by jonbjornn** [comment]
Ahh sorry you're right. Thanks for adding the example. It helped me clear up an error in my setup that was preventing it from loading. :grimacing:
